export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const classConstants = {
  GET_CLASSES_REQUEST: "GET_CLASSES_REQUEST",
  GET_CLASSES_SUCCESS: "GET_CLASSES_SUCCESS",
  GET_CLASSES_FAILURE: "GET_CLASSES_FAILURE",
  GET_UNREGISTERED_CLASSES_REQUEST: "GET_UNREGISTERED_CLASSES_REQUEST",
  GET_UNREGISTERED_CLASSES_SUCCESS: "GET_UNREGISTERED_CLASSES_SUCCESS",
  GET_UNREGISTERED_CLASSES_FAILURE: "GET_UNREGISTERED_CLASSES_FAILURE",
};

export const studentConstants = {
  GET_STUDENTS_REQUEST: "GET_STUDENTS_REQUEST",
  GET_STUDENTS_SUCCESS: "GET_STUDENTS_SUCCESS",
  GET_STUDENTS_FAILURE: "GET_STUDENTS_FAILURE",
  ADD_STUDENTS_REQUEST: "ADD_STUDENTS_REQUEST",
  ADD_STUDENTS_SUCCESS: "ADD_STUDENTS_SUCCESS",
  ADD_STUDENTS_FAILURE: "ADD_STUDENTS_FAILURE",
  UPDATE_STUDENTS_REQUEST: "UPDATE_STUDENTS_REQUEST",
  UPDATE_STUDENTS_SUCCESS: "UPDATE_STUDENTS_SUCCESS",
  UPDATE_STUDENTS_FAILURE: "UPDATE_STUDENTS_FAILURE",
  DELETE_STUDENTS_REQUEST: "DELETE_STUDENTS_REQUEST",
  DELETE_STUDENTS_SUCCESS: "DELETE_STUDENTS_SUCCESS",
  DELETE_STUDENTS_FAILURE: "DELETE_STUDENTS_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const attendanceConstants = {
  STUDENT_ATTENDANCE_REQUEST: "STUDENT_ATTENDANCE_REQUEST",
  STUDENT_ATTENDANCE_SUCCESS: "STUDENT_ATTENDANCE_SUCCESS",
  STUDENT_ATTENDANCE_FAILURE: "STUDENT_ATTENDANCE_FAILURE",
  CLASS_ATTENDANCE_REQUEST: "CLASS_ATTENDANCE_REQUEST",
  CLASS_ATTENDANCE_SUCCESS: "CLASS_ATTENDANCE_SUCCESS",
  CLASS_ATTENDANCE_FAILURE: "CLASS_ATTENDANCE_FAILURE",
  TODAY_ATTENDANCE_REQUEST: "TODAY_ATTENDANCE_REQUEST",
  TODAY_ATTENDANCE_SUCCESS: "TODAY_ATTENDANCE_SUCCESS",
  TODAY_ATTENDANCE_FAILURE: "TODAY_ATTENDANCE_FAILURE",
};
